name: col_dashboard
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20200923.3=h0e60522_0
  - altair=4.1.0=py_1
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py39hb82d6ee_2
  - arrow-cpp=3.0.0=py39h7424202_6_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - aws-c-cal=0.4.5=hffb5579_7
  - aws-c-common=0.5.1=h8ffe710_0
  - aws-c-event-stream=0.2.7=h141f785_0
  - aws-c-io=0.9.0=hc33d8df_1
  - aws-checksums=0.1.11=hc33d8df_2
  - aws-sdk-cpp=1.8.138=hac61a3b_3
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - base58=2.1.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - boto3=1.17.17=pyhd8ed1ab_0
  - botocore=1.20.17=pyhd8ed1ab_0
  - brotli=1.0.9=h0e60522_4
  - brotlipy=0.7.0=py39hb82d6ee_1001
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.17.1=h8ffe710_0
  - ca-certificates=2020.12.5=h5b45459_0
  - cachetools=4.2.1=pyhd8ed1ab_0
  - certifi=2020.12.5=py39hcbf5309_1
  - cffi=1.14.5=py39h0878f49_0
  - chardet=4.0.0=py39hcbf5309_1
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.4=py39h7bc7c5c_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - et_xmlfile=1.0.1=py_1001
  - freetype=2.10.4=h546665d_1
  - gflags=2.2.2=ha925a31_1004
  - gitdb=4.0.5=pyhd8ed1ab_1
  - gitpython=3.1.13=pyhd8ed1ab_0
  - glob2=0.7=py_0
  - glog=0.4.0=h0174b99_3
  - grpc-cpp=1.36.0=hd4140ee_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.7.0=py39hcbf5309_0
  - importlib_metadata=3.7.0=hd8ed1ab_0
  - intel-openmp=2020.3=h57928b3_311
  - ipykernel=5.5.0=py39h832f523_1
  - ipython=7.20.0=py39h832f523_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jdcal=1.4.1=py_0
  - jedi=0.18.0=py39hcbf5309_2
  - jinja2=2.11.3=pyh44b312d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py39hcbf5309_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - krb5=1.17.2=hbae68bd_0
  - lcms2=2.12=h2a16943_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libcurl=7.71.1=h4b64cdc_8
  - liblapack=3.9.0=8_mkl
  - libpng=1.6.37=h1d00b33_2
  - libprotobuf=3.15.2=h7755175_0
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.9.0=hb06d900_5
  - libthrift=0.13.0=hdfef310_6
  - libtiff=4.2.0=hc10be44_0
  - libutf8proc=2.6.1=hcb41399_0
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py39hb82d6ee_3
  - mistune=0.8.4=py39hb82d6ee_1003
  - mkl=2020.4=hb70f87d_311
  - mkl-service=2.3.0=py39h196d8e1_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py39hcbf5309_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.2.0=py39hcbf5309_0
  - numpy=1.20.1=py39h6635163_0
  - olefile=0.46=pyh9f0ad1d_1
  - openpyxl=3.0.6=pyhd8ed1ab_0
  - openssl=1.1.1j=h8ffe710_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.2=py39hf11a4ad_0
  - pandoc=2.11.4=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.1=pyhd8ed1ab_0
  - patsy=0.5.1=py39haa95532_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py39h1a9d4f7_2
  - pip=21.0.1=pyhd8ed1ab_0
  - plotly=4.14.3=pyh44b312d_0
  - plotly_express=0.4.1=py_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - protobuf=3.15.2=py39h415ef7b_0
  - pyarrow=3.0.0=py39hf9247be_6_cpu
  - pycparser=2.20=pyh9f0ad1d_2
  - pydeck=0.6.1=pyh44b312d_0
  - pygments=2.8.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py39hb82d6ee_2
  - pysocks=1.7.1=py39hcbf5309_3
  - python=3.9.2=h7840368_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pywin32=300=py39hb82d6ee_0
  - pywinpty=0.5.7=py39hde42818_1
  - pyyaml=5.4.1=py39hb82d6ee_0
  - pyzmq=22.0.3=py39h6e08c89_0
  - re2=2020.11.01=h0e60522_0
  - requests=2.25.1=pyhd3deb0d_0
  - retrying=1.3.3=py_2
  - s3transfer=0.3.4=pyhd8ed1ab_0
  - scipy=1.6.1=py39h14eb087_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py39hcbf5309_3
  - six=1.15.0=pyh9f0ad1d_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.8=ha925a31_3
  - sqlite=3.34.0=h8ffe710_0
  - statsmodels=0.12.2=py39h5d4886f_0
  - streamlit=0.77.0=pyhd8ed1ab_0
  - terminado=0.9.2=py39hcbf5309_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=h8ffe710_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py39hb82d6ee_1
  - traitlets=5.0.5=py_0
  - tzdata=2021a=he74cb21_0
  - tzlocal=2.1=pyh9f0ad1d_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - validators=0.18.2=pyhd3deb0d_0
  - vc=14.2=hb210afc_3
  - vs2015_runtime=14.28.29325=h5e1d092_3
  - watchdog=2.0.2=py39hcbf5309_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py39hcbf5309_4
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39hcbf5309_1006
  - winpty=0.4.3=4
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.3=h0e60522_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.8=h4e2f164_1
prefix: C:\Users\michael.lin\Miniconda3\envs\col_dashboard
